[project]
name = "prycegasstation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=4.2.25",
    "django-shortcuts>=1.6",
    "pillow>=11.3.0",
    "reportlab>=4.4.4",
    "xhtml2pdf>=0.2.17",
]
